plugins {
    id 'multiloader-loader'
    id 'fabric-loom'
}

fabricApi {
    configureDataGeneration()
}

base {
    archivesName = "fabric-${mod_id}-${minecraft_version}"
}


repositories {
    maven { url = "https://cursemaven.com" }
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.layered {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${parchment_minecraft}:${parchment_version}@zip")
    }
    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"
    implementation group: 'com.google.code.findbugs', name: 'jsr305', version: '3.0.1'
    implementation project(":common")

    modImplementation "curse.maven:supplementaries-412082:6974861"
    modImplementation "curse.maven:selene-499980:6978610"
}

loom {
    if (project(":common").file("src/main/resources/${mod_id}.accesswidener").exists()) {
        accessWidenerPath.set(project(":common").file("src/main/resources/${mod_id}.accesswidener"))
    }
    mixin {
        defaultRefmapName.set("${mod_id}.refmap.json")
    }
    runs {
        client {
            client()
            setConfigName("Fabric Client")
            ideConfigGenerated(true)
            runDir("run")
        }
        server {
            server()
            setConfigName("Fabric Server")
            ideConfigGenerated(true)
            runDir("run")
        }
        datagen {
            inherit client
            name "Data Generation"
            vmArg "-Dfabric-api.datagen"
            vmArg "-Dfabric-api.datagen.output-dir=${file("../common/src/main/generated/")}"
            vmArg "-Dfabric-api.datagen.modid=runiclib"

            runDir "build/datagen"
        }
    }
}

sourceSets.main.resources {
    srcDir project(":common").file('src/main/generated/').getAbsolutePath()
}
